"""empty message

Revision ID: 5b3f270b11bd
Revises: 61a6f53a2a04
Create Date: 2024-02-27 16:59:11.271566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3f270b11bd'
down_revision = '61a6f53a2a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ntfy_url', sa.String(), nullable=True))
        batch_op.drop_column('user_password')
        batch_op.drop_column('user_ntfy_url')
        batch_op.drop_column('user_name')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('user_ntfy_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('user_password', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('ntfy_url')
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
